### ISSUE TITLE
Does this repo still work?

### ISSUE THREAD

**Issue by pykao** [ykwon0407/isles2017_deprecated#1]
Hello, 

Does this repo still work for ISLES 2017 dataset?

Best, 
Po-Yu Kao

**Comment by ykwon0407** [comment]
Unfortunately, not. I made this repo public to check my previous code. (Please note that the codes are based on Theano, which is no longer developed.)
But I am sure that you can run this code with some modifications. Hope this finds you informative.

**Comment by pykao** [comment]
Thank you so much!
